# Generated by Django 2.2.6 on 2019-10-31 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20191031_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='like_total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
