# Generated by Django 2.2.6 on 2019-10-31 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_auto_20191031_0536'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='posted_on',
            field=models.DateTimeField(null=True),
        ),
    ]
