# Generated by Django 2.2.6 on 2019-11-01 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs', '0010_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likes',
            options={'ordering': ['-liked_date']},
        ),
        migrations.RenameField(
            model_name='likes',
            old_name='like_date',
            new_name='liked_date',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='like_author',
        ),
        migrations.AddField(
            model_name='likes',
            name='liked_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liked_author', to=settings.AUTH_USER_MODEL),
        ),
    ]
