# Generated by Django 2.2.6 on 2019-11-01 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_auto_20191101_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='liked_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likedauthor', to=settings.AUTH_USER_MODEL),
        ),
    ]
