# Generated by Django 2.2.6 on 2019-11-01 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0012_auto_20191101_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='like_total',
        ),
    ]
